apiVersion: v1
kind: Service
metadata:
  name: devops-practice-service
  labels:
    app: devops-practice
spec:
  type: LoadBalancer
  selector:
    app: devops-practice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    name: http
